import Image from 'next/image'

import { createAvatar } from '@dicebear/core'
import { initials } from '@dicebear/collection'

const getAvatar = (hackerName: string) =>
  createAvatar(initials, {
    seed: hackerName,
  }).toDataUriSync()

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HMOBSjrrMjo
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from '@/components/ui/table'
import { PwnCollegeHacker } from '@/types'

type LeaderboardProps = {
  hackers: PwnCollegeHacker[]
}

export function Leaderboard({ hackers }: LeaderboardProps) {
  return (
    <div className="w-full transition translate-y-0 hover:translate-y-1 shadow-lg overflow-hidden border-b border-zinc-200 sm:rounded-lg bg-white dark:border-gray-700 dark:bg-gray-900">
      <Table className="text-lg w-full">
        <TableHeader>
          <TableRow>
            <TableHead className="text-black dark:text-gray-200">
              Rank
            </TableHead>
            <TableHead className="text-black dark:text-gray-200"> </TableHead>
            <TableHead className="text-black dark:text-gray-200">
              Name
            </TableHead>
            <TableHead className="text-black dark:text-gray-200">
              Solves
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {hackers.map((hacker, idx) => (
            <TableRow key={hacker.pwnCollegeId}>
              <TableCell className="text-black dark:text-gray-300">
                #{idx + 1}
              </TableCell>
              <TableCell>
                {hacker.avatar ? (
                  <Image
                    className="rounded-full"
                    alt={hacker.name}
                    width={40}
                    height={40}
                    src={hacker.avatar}
                    placeholder="blur"
                    blurDataURL={hacker.image}
                  />
                ) : (
                  <Image
                    className="rounded-full"
                    alt={hacker.name}
                    width={40}
                    height={40}
                    src={getAvatar(hacker.name)}
                  />
                )}
              </TableCell>
              <TableCell className="text-black dark:text-gray-300">
                {hacker.name}
              </TableCell>
              <TableCell className="text-black dark:text-gray-300">
                {hacker.solves}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
